import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const files = [path.join(root, 'app.js'), path.join(root, 'config.js')];

for (const directory of ['functions', 'js']) {
  files.push(...await javascriptFiles(path.join(root, directory)));
}

for (const file of files) {
  const result = spawnSync(process.execPath, ['--check', file], { encoding: 'utf8' });
  assert.equal(result.status, 0, `${path.relative(root, file)} syntax failed:\n${result.stderr}`);
}

const [appSource, adminSource, adminBootstrapSource, adminCss, adminHtml, indexHtml, apiProxySource, themeSource, latencyAgentSource, latencyInstallerSource] = await Promise.all([
  readFile(path.join(root, 'app.js'), 'utf8'),
  readFile(path.join(root, 'js', 'admin.js'), 'utf8'),
  readFile(path.join(root, 'js', 'admin-bootstrap.js'), 'utf8'),
  readFile(path.join(root, 'admin.css'), 'utf8'),
  readFile(path.join(root, 'admin.html'), 'utf8'),
  readFile(path.join(root, 'index.html'), 'utf8'),
  readFile(path.join(root, 'functions', 'api', '[[path]].js'), 'utf8'),
  readFile(path.join(root, 'js', 'themes.js'), 'utf8'),
  readFile(path.join(root, 'latency-agent.py'), 'utf8'),
  readFile(path.join(root, 'install-latency.sh'), 'utf8'),
]);
const styleSource = await readFile(path.join(root, 'style.css'), 'utf8');
const unlockSource = await readFile(path.join(root, 'js', 'shared', 'unlock.js'), 'utf8');
const nodeQualitySource = await readFile(path.join(root, 'js', 'shared', 'nodequality.js'), 'utf8');
const installCommandSource = await readFile(path.join(root, 'js', 'install-command.js'), 'utf8');
const adminApiSource = await readFile(path.join(root, 'js', 'admin', 'api.js'), 'utf8');
const nqOptionsSource = await readFile(path.join(root, 'js', 'admin', 'nq-options.js'), 'utf8');
assert.match(adminSource, /import \{ nqOptionsHtml, readNqOptions \} from "\.\/admin\/nq-options\.js\?v=20260803-v1115"/, 'admin must import the configurable NodeQuality option helpers');
assert.match(nqOptionsSource, /data-nq-option="/, 'NodeQuality options must use stable data attributes for each select');
assert.match(nqOptionsSource, /运行 HardwareQuality 测试/, 'NodeQuality options must expose the four upstream questions');
assert.match(nqOptionsSource, /加速源/, 'NodeQuality options must expose the accelerator selector');
assert.match(nqOptionsSource, /data-nq-option="\$\{key\}"/, 'NodeQuality accelerator must use the stable data attribute template');
assert.doesNotMatch(adminSource, /showInstallProgress|showInstallCommands|data-copy-install|data-retry-install/, 'Agent deploy must not open an install-command dialog');
assert.match(adminSource, /agentInstallCommandFromPayload\(d, t\.id\);\s*await copyText\(cmd\)/, 'deploy must validate the credential-bound command before copying');
assert.match(adminSource, /含一次性凭据/, 'successful copy feedback must identify the one-time credential');
assert.match(installCommandSource, /credential_bound !== true[\s\S]*one_time_install_token/, 'copy validation must require a credential-bound one-time token');
assert.ok(installCommandSource.includes('Authorization:\\s*Bearer\\s+nsi_'), 'copy validation must require the one-time token in the command');
assert.ok(installCommandSource.includes('NSTATUS_AGENT_TOKEN\\s*='), 'copy validation must reject long-lived Agent tokens');
assert.match(adminSource, /data-target-id=/, 'deploy buttons must carry a stable target id');
assert.match(adminSource, /button\?\.dataset\.targetId \|\| button\?\.closest\("tr"\)\?\.dataset\.id/, 'deploy actions must resolve the stable button target id first');
assert.match(adminSource, /targetGroupOptions\(type, target\.group_name\)/, 'target grouping must be a VPS/Web selector');
assert.match(adminSource, /<select id="mProvider">/, 'provider must use a single selector');
assert.match(adminSource, /id="mProviderCustom"/, 'provider selector must support a custom vendor');
assert.match(adminSource, /location_source/, 'target editor must show the Agent location source');
assert.doesNotMatch(adminSource, /id="mLocation"|id="mCity"|\/api\/catalog\/cities/, 'country and city must not be manually editable');
assert.match(adminSource, /到期时间（可选）/, 'target expiry must be clearly optional');
assert.match(adminSource, /formField\("机器类型"/, 'target editor must label line_type as machine type');
assert.doesNotMatch(adminSource, /formField\("线路类型"/, 'target editor must not expose the old line type label');
assert.match(adminSource, /currencyOptionsHtml\(target\.currency \|\| "USD"\)/, 'currency must use the supported selector');
assert.match(adminSource, /id="mNoPublicIp"/, 'VPS editor must expose the no-public-IP option');
assert.match(adminSource, /const cfDetails = noPublicIp[\s\S]*\? ""/, 'no-public-IP targets must hide Cloudflare status in admin');
assert.match(adminSource, /\/api\/latency-agents/, 'admin must manage independent Latency nodes');
assert.match(adminSource, /install-command\?node_id=/, 'Latency nodes must have an independent installer command');
assert.doesNotMatch(appSource, /pingRows \|\| cardLatencyRow/, 'Latency rendering must not fall back to Ping rows');
assert.match(appSource, /!c\?\.missed && c\?\.error/, 'missed checks must not also render a misleading failure message');
assert.doesNotMatch(adminCss, /min-width:\s*(?:1080|1280)px/, 'probe table must not regress to the old extra-wide layout');
assert.match(adminCss, /width:\s*min\(980px,\s*calc\(100vw - 44px\)\)/, 'admin content width should match the frontend rhythm');
assert.doesNotMatch(adminCss, /\.stat(?:\.\w+)?::before/, 'dashboard stats must not render decorative edge stripes');
assert.match(adminCss, /\.group-by-menu\s*\{[\s\S]*box-shadow:/, 'group selector must use the custom admin menu');
assert.match(adminSource, /data-group-value/, 'group selector must use structured custom options');
assert.match(adminCss, /\.modal::\-webkit-scrollbar\s*\{[\s\S]*display:\s*none/, 'long edit dialogs must hide the native scrollbar');
assert.match(adminCss, /html,\s*body\s*\{[\s\S]*max-width:\s*100%[\s\S]*overflow-x:\s*hidden/, 'admin pages must prevent viewport-level horizontal overflow');
assert.match(adminCss, /\.modal\s*\{[\s\S]*min-width:\s*0[\s\S]*max-width:\s*100%[\s\S]*overflow-x:\s*hidden/, 'admin dialogs must stay within the mobile viewport');
assert.match(adminCss, /@media \(max-width: 720px\)\s*\{[\s\S]*\.f input,\s*\.f select,\s*\.f textarea,[\s\S]*font-size:\s*16px/, 'mobile form controls must use a sufficiently specific 16px rule to prevent iOS focus zoom');
assert.match(adminCss, /@media \(max-width: 560px\)\s*\{\s*\.form-grid\s*\{\s*grid-template-columns:\s*minmax\(0,\s*1fr\)/, 'mobile dialog form grids must collapse to one shrinkable column');
assert.match(adminCss, /\.targets-table tbody tr\.group-sep\s*\{[\s\S]*grid-column:\s*1 \/ -1[\s\S]*width:\s*100%/, 'mobile target group headings must span the full card-list width');
assert.match(adminCss, /\.targets-table tbody tr\.group-sep > td\s*\{[\s\S]*width:\s*100%/, 'mobile target group cells must override the desktop first-column width');
assert.match(adminCss, /#tTable \.table-scroll\s*\{\s*overflow:\s*visible/, 'only the card-based target table may overflow on mobile');
assert.match(adminHtml, /href="\/admin\.css\?v=20260803-v1115"/, 'custom admin paths must load CSS from the site root');
assert.match(adminHtml, /src="\/config\.js\?v=/, 'custom admin paths must load runtime config from the site root');
assert.match(adminHtml, /src="\/vendor\/chart\.umd\.min\.js\?v=/, 'custom admin paths must load Chart.js from the site root');
assert.match(adminHtml, /src="\/js\/admin-bootstrap\.js\?v=20260803-v1115"/, 'admin login must install a startup failure guard');
assert.match(adminHtml, /src="\/js\/admin\.js\?v=20260803-v1115"/, 'custom admin paths must load the admin module from the site root');
assert.match(adminBootstrapSource, /后台脚本加载失败，请刷新页面/, 'admin startup failures must be visible on the login form');
assert.match(adminBootstrapSource, /loginButton\.onclick = \(event\)/, 'the admin module must replace the startup guard only after it loads');
assert.match(adminSource, /window\.__NIE_ADMIN_READY__ = true;[\s\S]*nie-admin-ready/, 'the admin module must dismiss its startup guard after binding controls');
assert.match(adminHtml, /id="pingIntervalSec"[^>]*type="number"[^>]*min="5"[^>]*max="300"[^>]*step="1"/, 'Ping settings must expose an integer interval from 5 to 300 seconds');
assert.doesNotMatch(adminHtml, /1 秒时最多启用 5 个目标/, 'obsolete one-second target guidance must be removed');
assert.match(adminSource, /apiAdmin\("\/api\/ping-config"[\s\S]*method:\s*"PATCH"[\s\S]*ping_interval_sec:\s*interval/, 'Ping interval changes must use the protected configuration endpoint');
assert.match(adminCss, /\.ping-interval-row\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto auto[\s\S]*\.ping-interval-control input\s*\{[\s\S]*font-size:\s*16px/, 'Ping interval controls must remain stable and zoom-safe on mobile');
assert.match(adminSource, /selectedTargetIds[\s\S]*targetBulkBarHtml[\s\S]*bulkTargetModal/, 'admin must support selecting and batch-editing VPS targets');
assert.match(adminSource, /apiAdmin\("\/api\/targets\/bulk"[\s\S]*method:\s*"PATCH"/, 'batch target editing must use one protected Worker request');
assert.match(adminSource, /openBulkTargetPicker\(false, \(\) => bulkTaskModal\("nodequality"\), 50\)/, 'batch NodeQuality selection must match the Worker batch limit');
assert.match(adminSource, /async function queueBulkAgentTasks[\s\S]*const options = action === "nodequality" \? readNqOptions\(byId\("modal"\)\) : undefined;[\s\S]*closeModal\(\);[\s\S]*JSON\.stringify\(\{ agent_ids: ids, action, options \}\)/, 'batch Agent tasks must capture NodeQuality options before closing the modal and submit them in one request');
assert.match(adminSource, /apiAdmin\("\/api\/agent-tasks"[\s\S]*method:\s*"POST"[\s\S]*60000\)/, 'bulk Agent task queueing must use a bounded long-running admin request');
assert.match(adminSource, /async function queueBulkAgentTasks[\s\S]*selectedTargetIds\.clear\(\);[\s\S]*closeModal\(\);[\s\S]*apiAdmin\("\/api\/agent-tasks"/, 'bulk Agent queueing must close the modal before the long-running request');
assert.match(adminSource, /async function queueBulkAgentTasks[\s\S]*catch \(error\) \{\s*toast\(error\.message, "err"\);[\s\S]*await loadAgentTasks\(\)/, 'bulk queue failures must refresh task state after closing the modal');
assert.match(adminSource, /JSON\.stringify\(\{ agent_id: target\.id, action, options: action === "nodequality" \? readNqOptions\(byId\("modal"\)\) : undefined \}\)/, 'single Agent tasks must submit NodeQuality options');
assert.match(adminSource, /nqOptionsHtml\(\)/, 'NodeQuality confirmation dialogs must offer the configurable test options');
assert.match(adminSource, /只有左侧已勾选的字段会被覆盖/, 'batch editor must explain selective field updates');
assert.match(adminCss, /@media \(max-width: 720px\)\s*\{[\s\S]*\.target-bulk-bar\s*\{[\s\S]*flex-wrap:\s*wrap/, 'batch target controls must wrap on mobile');
assert.match(adminSource, /target-action-main[\s\S]*targetActionsHtml\(target\)[\s\S]*betaTaskControlsHtml\(target\)/, 'standard target actions must render before Beta tasks');
assert.match(adminCss, /\.beta-task-actions\s*\{[\s\S]*border-top:/, 'Beta tasks must form a distinct action group');
assert.match(adminCss, /\.beta-task-meta\s*\{[\s\S]*flex-wrap:\s*wrap[\s\S]*justify-content:\s*flex-start/, 'Beta metadata must wrap without creating a detached right-aligned label');
assert.match(adminHtml, /settings-subnav[\s\S]*data-settings-tab="appearance"[\s\S]*data-settings-tab="system"/, 'settings must expose a secondary category menu');
assert.match(adminHtml, /data-settings-panel="appearance"[\s\S]*data-settings-panel="system"/, 'settings categories must own separate content panels');
assert.match(adminCss, /\.settings-panel-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/, 'desktop settings panels must use a restrained two-column layout');
assert.match(adminCss, /@media \(max-width: 820px\) \{[\s\S]*\.settings-panel-grid\s*\{\s*grid-template-columns:\s*1fr/, 'mobile settings panels must collapse to one column');
assert.match(adminHtml, /id="sAdminPath"/, 'admin settings must expose the custom entry path');
assert.match(adminHtml, /id="sAgentOrigin"/, 'admin settings must expose the Agent connection origin');
assert.match(adminSource, /agent_public_base:[\s\S]*input\?\.value\.trim/, 'Agent connection origin must persist through authenticated settings');
assert.doesNotMatch(adminSource, /prompt\("为受保护备份|prompt\("请输入敏感备份密码/, 'protected backup flows must not depend on native prompt dialogs');
assert.match(adminSource, /function requestBackupPassword\([\s\S]*id="backupPassword"[\s\S]*value\.length < 10[\s\S]*openModal\(\)/, 'protected backup must collect and validate its password in the accessible admin modal');
assert.match(adminSource, /requestBackupPassword\(\{ restore: true \}\)/, 'protected restore must reuse the bounded password modal');
assert.match(adminSource, /apiAdmin\("\/api\/backup\/export"[\s\S]*60000\)/, 'protected backup export must use a bounded long-running admin request');
assert.match(appSource, /fetchWithTimeout\(api\(`\/api\/nq\//, 'public NodeQuality reports must use a bounded request');
assert.match(adminApiSource, /defaultTimeoutMs\s*=\s*12_000[\s\S]*if \(!options\.signal\)[\s\S]*withTimeout\(defaultTimeoutMs/, 'all direct Admin API calls need a default timeout');
assert.match(adminApiSource, /请求可能仍在服务端继续执行，请稍后刷新查看/, 'admin task timeouts must explain that the request may still be running server-side');
assert.match(adminSource, /任务状态刷新失败[\s\S]*task-load-warning/, 'task polling failures must surface a visible warning');
assert.match(adminSource, /async function queueAgentTask[\s\S]*catch \(error\) \{[\s\S]*await loadAgentTasks\(\)/, 'single-machine queue failures must refresh task state');
assert.match(adminSource, /id="backupStatus"[\s\S]*正在加密 Agent Token/, 'protected backup must expose persistent progress next to its controls');
assert.match(adminSource, /install-command\.js\?v=20260803-v1115/, 'Agent and Latency install clipboard fixes must use the current cache key');
assert.match(adminSource, /latencyInstallCommandFromPayload\(data, node\.id\);\s*await copyText\(command\)/, 'Latency deploy must validate and copy the one-time command without opening a dialog');
const latencyDeploySource = adminSource.slice(adminSource.indexOf('async function deployLatencyNode'), adminSource.indexOf('async function loadPings'));
assert.doesNotMatch(latencyDeploySource, /openModal\(\)/, 'Latency deploy must not open an install-command dialog');
assert.match(adminHtml, /id="sAppUpdate"/, 'admin settings must expose the application update center');
assert.match(adminSource, /\/api\/system\/update\$\{refresh/, 'update center must check the Worker update API');
assert.doesNotMatch(adminSource, /appUpdateToken|github_token|appUpdateRepository/, 'update center must not collect repositories or GitHub credentials');
assert.match(adminSource, /function showAppUpdateChangelog\(\)[\s\S]*openModal\(\)/, 'changelog must open in the admin modal');
assert.match(adminSource, /function showAppUpdateGuide\(\)[\s\S]*NIE-SLA Online Update[\s\S]*Run workflow[\s\S]*openModal\(\)/, 'update guide must explain the no-input Actions workflow');
assert.doesNotMatch(adminSource, /data\.release_url[\s\S]*href=/, 'changelog must not link away to GitHub');
assert.match(adminSource, /每 \$\{escapeHtml\(data\.automatic_check_hours \|\| 6\)\} 小时自动检查/, 'update center must explain scheduled checks');
assert.match(adminSource, /infoRow\("版本", health\.version/, 'system information must display the Worker version');
assert.match(adminSource, /id="mTrafficResetDay"[\s\S]*min="1" max="31"/, 'target editor must expose an independent monthly traffic reset day');
assert.match(adminSource, /traffic_reset_day:\s*byId\("mType"\)/, 'target saves must persist the independent traffic reset day');
assert.match(adminSource, /流量重置日与 VPS 到期时间完全独立/, 'traffic settings must explain expiry/reset separation');
assert.match(adminSource, /修改流量重置日会立即切换当前统计周期/, 'changing the reset day must require an explicit warning');
assert.match(adminSource, /按已有的每日记录重新汇总/, 'reset-day warning must explain daily traffic recalculation');
assert.doesNotMatch(adminSource, /新的基线重新累计/, 'reset-day changes must not discard recorded daily traffic');
assert.doesNotMatch(adminSource, /流量会按到期日号|按照到期时间的日号每月重置/, 'traffic reset guidance must not depend on expiry');
assert.match(indexHtml, /app\.js\?v=20260803-v1115/, 'frontend cache key must publish the current release');
assert.match(indexHtml, /style\.css\?v=20260803-v1115/, 'frontend CSS cache key must publish the current release');
assert.doesNotMatch(appSource, /traffic\.reset === 'expiry-day'/, 'frontend traffic labels must not depend on expiry reset mode');
assert.match(adminSource, /JSON\.stringify\(\{ admin_path: value \}\)/, 'admin settings must persist the custom entry path');
assert.match(indexHtml, /class="theme-pending"[\s\S]*id="themeBoot"[\s\S]*id="themeCanvas"/, 'theme runtime must wait behind a first-paint shell');
assert.match(adminHtml, /id="sAppearance"/, 'admin must provide a centralized appearance editor');
assert.match(adminHtml, /data-p="themes"[\s\S]*id="pg-themes"[\s\S]*id="themeZip"[\s\S]*id="themeTable"/, 'admin must expose a dedicated theme package page');
assert.doesNotMatch(adminHtml, /id="pg-plugins"|pluginZip|uploadPluginBtn/, 'plugin package UI must stay removed');
assert.match(adminSource, /appearanceSections/, 'admin must expose grouped frontend appearance fields');
assert.match(adminSource, /brand_home_url[\s\S]*header_right_image_width/, 'admin must expose brand and header media controls');
assert.match(adminSource, /show_header[\s\S]*show_chart[\s\S]*show_vps_details/, 'admin must expose frontend section visibility controls');
assert.match(appSource, /data\?\.frontend\?\.appearance/, 'frontend must consume public appearance settings');
assert.match(appSource, /--appearance-brand-logo-height/, 'frontend must apply the configured brand dimensions');
assert.match(adminSource, /JSON\.stringify\(\{ appearance \}\)/, 'admin must save frontend appearance settings');
assert.match(adminSource, /\/api\/themes\/manage[\s\S]*\/api\/themes\/upload[\s\S]*x-theme-sha256/, 'admin must list and integrity-check theme packages');
assert.doesNotMatch(adminSource, /\/api\/(?:extensions|plugins)|pluginZip|data-extension-action/, 'generic extension and plugin management must stay removed');
assert.match(appSource, /js\/themes\.js[\s\S]*initializeFrontendTheme\(\)/, 'frontend must initialize the active theme runtime');
assert.match(themeSource, /frame\.sandbox = 'allow-scripts'/, 'canvas themes must execute in a script-only sandbox');
assert.doesNotMatch(themeSource, /allow-same-origin/, 'canvas themes must never share the application origin');
assert.match(themeSource, /addEventListener\('load', \(\) => finish\(\)/, 'successful theme resource loads must not be treated as errors');
assert.match(themeSource, /THEME_API_RESOURCES = new Set\(\['status', 'checks', 'metrics', 'pings', 'latency'\]\)/, 'canvas requests must use the explicit read-only resource allowlist');
assert.match(themeSource, /permissions\?\.includes\('status:read'\)/, 'canvas requests must require the read-only theme permission');
assert.match(apiProxySource, /x-theme-sha256/, 'Pages proxy preflight must allow theme integrity headers');
assert.doesNotMatch(apiProxySource, /x-extension-filename|x-extension-sha256/, 'Pages proxy must not retain extension upload headers');
assert.doesNotMatch(appSource, /meta-provider">🏪/, 'provider metadata must use typography instead of decorative emoji');
assert.match(appSource, /function serviceDisplayName[\s\S]*startsWith\(normalize\(provider\)\)/, 'VPS titles must prefix the provider without duplicating existing provider names');
assert.doesNotMatch(appSource, /class="meta-badge meta-provider"/, 'provider must not be repeated as a separate frontend badge');
assert.doesNotMatch(appSource, /serviceMetaHtml|class="service-target"/, 'coarse probe-region labels must not appear in VPS rows');
assert.doesNotMatch(appSource, /serviceLatencySourcesHtml|service-latency-source/, 'VPS rows must not display external Latency Agent names or values');
assert.match(appSource, /\/api\/latency\?[\s\S]*externalLatencyChartSeries/, 'detailed latency charts must retain external Latency Agent history');
assert.match(appSource, /function serviceCloudflareLatencyHtml[\s\S]*Cloudflare 延迟/, 'VPS rows must retain the unnamed Cloudflare latency value');
assert.match(appSource, /function isTargetStale\(\)\s*\{[\s\S]*return false;/, 'successful Web checks must not be relabelled as delayed by a second heartbeat rule');
assert.match(adminSource, /function isStatusStale\(\)\s*\{\s*return false;/, 'admin Web status must use the latest check result without a second stale state');
assert.doesNotMatch(appSource, /meta-line">🔀/, 'line type metadata must use typography instead of decorative emoji');
assert.doesNotMatch(appSource, /`📍 \$\{t\.location\}`/, 'fallback location metadata must not add decorative emoji');
assert.match(appSource, /apac:\s*'亚太'/, 'probe region labels must be fully Chinese');
assert.match(appSource, /wnam:\s*'北美西部'/, 'Western North America label must stay Chinese');
assert.doesNotMatch(appSource, /apac:\s*'APAC'/, 'probe region labels must not mix English abbreviations');
assert.doesNotMatch(appSource, /wnam:\s*'美国西部'/, 'region labels must use the shared Chinese wording');
assert.match(appSource, /function targetLocationLabel/, 'status page must format country + city labels');
assert.match(appSource, /s\.source === 'agent'[\s\S]*Agent 在线率/, 'Agent availability bars must distinguish heartbeat uptime from probe counts');
assert.match(appSource, /service-latency\$\{hasLatency \? '' : ' is-placeholder'\}/, 'targets without public latency must retain an invisible alignment slot');
assert.match(appSource, /import \{ targetSlaPercentage \} from '\.\/js\/shared\/sla\.js'/, 'VPS rows must calculate SLA with the tested shared helper');
assert.match(appSource, /const slaLabel = [\s\S]*最近 30 天 SLA[\s\S]*service-sla-value">\$\{slaValue\}/, 'status rows must expose the rolling 30-day SLA while keeping the visible value concise');
assert.doesNotMatch(appSource, /service-sla-period|>30天<\/span>/, 'status rows must not repeat the SLA period beside every percentage');
assert.doesNotMatch(appSource, /<div class="service-uptime/, 'VPS rows must not retain the old Agent online label slot');
assert.match(styleSource, /\.service-latency\.is-placeholder\s*\{[\s\S]*visibility:\s*hidden/, 'missing latency must keep its desktop and mobile grid slot');
assert.match(styleSource, /\.service-sla\.sla-good \.service-sla-value\s*\{\s*color:\s*#16804a/, 'healthy SLA values must use a distinct green state');
assert.match(styleSource, /\.service-sla\.sla-bad \.service-sla-value\s*\{\s*color:\s*#c2413a/, 'low SLA values must use a distinct red state');
assert.doesNotMatch(styleSource, /\.service\.no-latency\s*\{\s*grid-template-columns:/, 'missing latency must not collapse the shared column layout');
assert.doesNotMatch(appSource, /status_source === 'agent'[\s\S]{0,120}Cloudflare 探测记录/, 'Agent day bars must not be labelled as Cloudflare probe history');
assert.match(appSource, /vps-info-toggle/, 'mobile VPS details must be collapsible');
assert.match(appSource, /openNodeQualityReport/, 'frontend must open NodeQuality reports');
assert.match(appSource, /const primary = \['tiktok', 'disney', 'netflix', 'youtube', 'amazonpv', 'chatgpt'\]/, 'public VPS rows must show the six primary unlock services');
assert.match(unlockSource, /if \(\/仅\\s\*自制\|仅\\s\*网页\|仅\\s\*app\|部分\|partial\/\.test\(status\)\) return 'dns';[\s\S]*if \(\/解锁\|原生\|unlocked\|native\|yes\|ok\/\.test\(status\)\) return 'good';[\s\S]*if \(\/dns\/\.test\(status\) \|\| \/dns\/\.test\(method\)\) return 'dns'/, 'successful unlock statuses must stay green even when the method is DNS');
assert.match(appSource, /\$\{metaBadges[\s\S]*\$\{unlockStrip\}\s*<\/div>\s*<div class="service-status">/, 'unlock summary must stay with the VPS metadata above the uptime bars');
assert.doesNotMatch(appSource, /unlockDetailSection|vps-unlock-section/, 'unlock checks must not be duplicated in the lower VPS details panel');
assert.match(unlockSource, /失败\|未解锁\|不支持\|封锁\|屏蔽\|禁止\|禁会员\|中国/, 'China-only unlock status must be classified as failed');
assert.match(appSource, /stateName === 'bad'[\s\S]*if \(\/屏蔽\/\.test\(status\)\) return '屏蔽';/, 'blocked unlock services must label the red box');
assert.match(appSource, /ping_stats[\s\S]*renderPingLossStats/, 'TCP Ping must render per-target packet-loss statistics');
assert.match(appSource, /max_points_per_target:\s*String\(\(\{\s*['"]1h['"]:\s*360,[\s\S]*['"]24h['"]:\s*480/, 'TCP Ping history must use the bounded standard point budgets');
assert.doesNotMatch(appSource, /include_loss:\s*['"]1['"]|pingLossOverlayPlugin|pingLossLaneBounds/, 'TCP Ping must not request or draw chart-internal packet-loss overlays');
const tcpPingChartSource = appSource.slice(appSource.indexOf('async function updatePingChart()'), appSource.indexOf('function fallbackPingStats'));
assert.doesNotMatch(tcpPingChartSource, /packetLoss:\s*true|label:\s*['"]丢包率['"]/, 'TCP Ping chart datasets must contain latency lines only');
assert.match(appSource, /function buildLatencyChartDatasets[\s\S]*packetLoss:\s*true[\s\S]*backgroundColor:\s*['"]rgba\(250, 204, 21, 0\.10\)['"][\s\S]*fill:\s*['"]origin['"]/, 'Latency must keep its restrained packet-loss area');
assert.match(appSource, /ping-current-value[\s\S]*<small>丢包<\/small>/, 'TCP Ping summaries must show current latency and packet loss together');
assert.match(appSource, /options\.scales\.y\.min\s*=\s*0/, 'TCP Ping latency axes must never show negative milliseconds');
assert.match(appSource, /legend\.display\s*=\s*!\[['"]latency['"],\s*['"]ping['"]\]\.includes\(state\.selectedMetric\)/, 'Latency and TCP Ping summaries must replace the duplicate chart legend');
assert.match(appSource, /function buildLatencyChartDatasets[\s\S]*sourceId:\s*source\.id[\s\S]*packetLoss:\s*true[\s\S]*rgba\(250, 204, 21, 0\.10\)/, 'Latency must use independently selectable source lines and restrained packet-loss spikes');
assert.match(appSource, /function lineDataset[\s\S]*latencySourceId:/, 'Latency line datasets must retain their selectable source identity');
assert.match(appSource, /function cloudflareLatencyChartSeries[\s\S]*function externalLatencyChartSeries[\s\S]*function latencySamples/, 'Latency summaries must normalize Cloudflare and external agents as independent sources');
assert.match(appSource, /normalizeLatencySample\(sourceId, check\)/, 'Latency charts must treat readings beyond the shared one-second probe budget as packet loss');
assert.match(appSource, /state\.latencyVisibleSources\s*=\s*nextPingTargetSelection[\s\S]*applyLatencySourceSelection/, 'Latency source summaries must support the same additive filtering interaction as TCP Ping');
assert.match(appSource, /unlock-service-label[\s\S]*unlock-country/, 'unlock checks must render service labels above country boxes');
assert.match(appSource, /function unlockCountryCode[\s\S]*ALISG|normalized\.endsWith\(code\)/, 'unlock regions must normalize provider values to two-letter country codes');
assert.match(styleSource, /\.unlock-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(6, 40px\)[\s\S]*grid-template-rows:\s*10px 17px/, 'unlock checks must use a compact two-row six-column grid');
assert.match(styleSource, /\.unlock-country\.good\s*\{\s*color:\s*#17623b;\s*background:\s*#ccebd9/, 'successful unlock checks must use a readable light-green state');
assert.match(styleSource, /\.unlock-country\.dns\s*\{\s*color:\s*#765708;\s*background:\s*#f2e2ad/, 'DNS unlock checks must use a readable light-yellow state');
assert.match(styleSource, /\.unlock-country\.bad\s*\{\s*color:\s*#8e3035;\s*background:\s*#f2cccc/, 'failed unlock checks must use a readable light-red state');
assert.match(styleSource, /@media \(max-width: 760px\) \{[\s\S]*\.unlock-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(6, minmax\(0, 1fr\)\)/, 'mobile unlock checks must fit all six columns into the VPS metadata width');
assert.match(styleSource, /\.metric-tabs\s*\{[\s\S]*flex-wrap:\s*nowrap[\s\S]*overflow-x:\s*auto/, 'metric tabs must remain on one horizontally scrollable row');
assert.match(styleSource, /\.chart-toolbar\s*>\s*:first-child\s*\{[\s\S]*max-width:\s*720px[\s\S]*\.metric-tabs\s*\{[\s\S]*justify-content:\s*flex-end/, 'desktop chart metric tabs must align with the right-side range controls');
assert.match(styleSource, /@media \(max-width: 760px\) \{[\s\S]*\.metric-tabs\s*\{[\s\S]*justify-content:\s*flex-start/, 'mobile chart metric tabs must keep the first label reachable');
assert.match(adminSource, /setupSettingsTabs\(\)/, 'settings must initialize the secondary category menu');
assert.match(adminSource, /function renderVpsSla\(data\)[\s\S]*targetSlaPercentage/, 'dashboard must show fleet-wide VPS SLA instead of an unused default Agent');
assert.doesNotMatch(adminSource, /api\("\/api\/agent\/metrics"\)/, 'dashboard must not request a hard-coded default Agent');
assert.match(adminSource, /accountSaveStatus\("正在验证并更新账号密码/, 'account updates must show progress and errors inside the settings card');
assert.match(adminSource, /id="accountCurrentUsername"[\s\S]*readonly[\s\S]*id="accountUsername"[\s\S]*autocomplete="off"/, 'account settings must separate the current username from the autofill-resistant new username');
assert.match(adminSource, /current_username:\s*currentUsername[\s\S]*change_username:\s*changeUsername/, 'account updates must declare whether the username should change');
assert.match(adminSource, /result\.username !== username[\s\S]*result\.username_changed/, 'account updates must verify the server-confirmed username before reporting success');
assert.match(adminSource, /id="pColor" type="color"/, 'Ping targets must expose a configurable chart color');
assert.match(adminSource, /id="latencyNodeColor" type="color"/, 'Latency nodes must expose a configurable chart color');
assert.match(appSource, /configuredChartColor\(tgt\.color/, 'TCP Ping charts must use the configured target color');
assert.match(appSource, /configuredChartColor\(source\.color/, 'external Latency charts must use the configured node color');
assert.match(styleSource, /@media \(max-width: 760px\) \{[\s\S]*\.service-list\s*\{\s*padding:\s*0 14px 14px 18px/, 'mobile VPS rows must reclaim horizontal space');
assert.match(styleSource, /@media \(max-width: 760px\) \{[\s\S]*\.chart-canvas-wrap\s*\{\s*height:\s*232px/, 'mobile charts must retain a readable height');
assert.match(appSource, /const mobileChart = isMobileChartViewport\(\)/, 'Chart.js must apply its mobile label profile');
assert.match(appSource, /isGpu && !hasGpuData\(info\)/, 'GPU tabs must stay hidden on VPS nodes without detected GPU hardware');
assert.match(styleSource, /\.vps-info-item\s*\{[\s\S]*flex-direction:\s*column/, 'VPS detail labels and values must keep their visual hierarchy');
assert.doesNotMatch(styleSource, /\.vps-info-body\s*\{[^}]*font-family:/, 'VPS details must inherit the same font stack as the rest of the page');
assert.match(appSource, /targetHasNodeQuality/, 'frontend must expose NQ only for targets with reports');
assert.match(appSource, /event\.target\.closest\('\.nq-close'\)\s*\|\|\s*event\.target\.classList\.contains\('nq-modal-backdrop'\)/, 'NQ tabs must not close the modal');
assert.match(styleSource, /\.nq-modal\s*\{[\s\S]*width:\s*min\(640px/, 'NQ modal should have a restrained desktop width');
assert.match(appSource, /service-title-line[\s\S]*nqButton/, 'classic VPS cards must place NQ beside the name');
assert.match(styleSource, /\.nq-image\s*\{[\s\S]*width:\s*min\(100%,\s*760px\)/, 'NQ images must use a readable content width');
assert.match(styleSource, /@media \(max-width: 760px\) \{[\s\S]*\.nq-image\s*\{\s*width:\s*100%/, 'NQ images must use the full mobile content width');
assert.doesNotMatch(styleSource, /@media \(max-width: 420px\) \{[\s\S]*\.nq-image\s*\{\s*width:\s*88%/, 'compact iPhones must not waste NQ image width');
assert.doesNotMatch(styleSource, /\.nq-modal-backdrop\s*\{\s*padding:\s*4px/, 'compact NQ dialogs must retain visible breathing room at the viewport edge');
assert.match(styleSource, /\.nq-ansi-panel\s*\{[\s\S]*-webkit-overflow-scrolling:\s*touch/, 'ANSI reports must support touch scrolling on iPhone');
assert.match(styleSource, /@media \(max-width: 560px\) \{[\s\S]*\.nq-ansi-panel,[\s\S]*\.nq-network-scroll\s*\{\s*overflow-x:\s*auto[\s\S]*\.nq-ansi-panel \.nq-ansi,[\s\S]*white-space:\s*pre[\s\S]*word-break:\s*normal/, 'mobile ANSI reports must preserve terminal columns inside local horizontal scrollers');
assert.match(styleSource, /\.nq-panels\s*\{[^}]*flex:\s*1 1 auto[^}]*width:\s*100%[^}]*min-width:\s*0[^}]*overflow-x:\s*hidden[^}]*overflow-y:\s*auto/, 'NQ report content must constrain horizontal scrolling to the active panel');
assert.match(styleSource, /\.nq-ansi-panel\s*\{[^}]*width:\s*100%[^}]*min-width:\s*0[^}]*overflow-x:\s*auto/, 'ANSI reports must own their horizontal scrolling region');
assert.match(styleSource, /@media \(max-width: 560px\) \{[\s\S]*\.nq-ansi\s*\{\s*font-size:\s*10px/, 'phone-sized NQ terminals must remain readable while the ANSI panel owns overflow');
assert.match(styleSource, /@media \(max-width: 420px\) \{[\s\S]*\.nq-ansi\s*\{\s*font-size:\s*10px/, 'compact iPhones must preserve the readable NQ terminal size');
assert.match(styleSource, /@media \(max-width: 420px\) \{[\s\S]*\.nq-modal-backdrop\s*\{[\s\S]*safe-area-inset-bottom[\s\S]*\.nq-modal\s*\{[^}]*safe-area-inset-top/, 'compact iPhones must preserve NQ safe-area spacing');
assert.match(nodeQualitySource, /panels\.scrollTop\s*=\s*0/, 'switching NQ tabs must reset vertical scroll');
assert.match(nodeQualitySource, /tab\.kind === 'image' && imageSrc[\s\S]*class="nq-image"/, 'hosted network and route terminal images must take display priority');
assert.match(nodeQualitySource, /renderNqNetworkReportHtml[\s\S]*renderNqRouteReportHtml/, 'text-only network and route reports must keep dedicated fallbacks');
assert.match(adminSource, /data-a="task-nq"/, 'admin must expose the fixed NodeQuality action');
assert.match(adminSource, /data-a="task-unlock"/, 'admin must expose the fixed IPv4 unlock action');
assert.match(adminSource, /\/api\/agent-tasks/, 'Beta actions must use the fixed task API');
assert.match(adminSource, /shouldOpenNodeQualityReport\(task\)[\s\S]*showNodeQualityReport/, 'all successful NQ tasks must try the structured report instead of raw task JSON');
assert.doesNotMatch(adminSource, /task\.result\?\.report_saved[\s\S]*showNodeQualityReport/, 'legacy report_saved flags must not select the admin NQ dialog type');
assert.match(adminSource, /apiPublic\(`\/api\/nq\/\$\{encodeURIComponent\(target\.id\)\}`\)[\s\S]*buildNqModalHtml\(report\)/, 'admin NQ details must load and render the public structured report');
assert.match(adminSource, /catch \(error\) \{[\s\S]*root\.innerHTML = `<div class="nq-modal-backdrop">[\s\S]*这条任务没有可展示的完整报告，请重新运行 NQ/, 'missing legacy reports must remain in the NodeQuality dialog with an actionable message');
assert.doesNotMatch(adminSource, /catch \(error\) \{\s*closeAdminNodeQualityReport\(\);\s*showAgentTaskDiagnostic/, 'successful NQ tasks must not fall back to raw JSON when the report is unavailable');
assert.match(adminCss, /\.nq-modal\s*\{[\s\S]*width:\s*min\(640px[\s\S]*\.nq-ansi-panel\s*\{[\s\S]*width:\s*100%[\s\S]*-webkit-overflow-scrolling:\s*touch[\s\S]*@media \(max-width: 420px\) \{[\s\S]*\.nq-ansi\s*\{\s*font-size:\s*10px/, 'admin must preserve the desktop and readable compact iPhone NQ report layout');
assert.match(adminCss, /@media \(max-width: 560px\) \{[\s\S]*\.nq-ansi-panel,[\s\S]*\.nq-network-scroll\s*\{\s*overflow-x:\s*auto[\s\S]*\.nq-ansi-panel \.nq-ansi,[\s\S]*white-space:\s*pre[\s\S]*word-break:\s*normal/, 'admin mobile ANSI reports must preserve terminal columns inside local horizontal scrollers');
assert.match(adminCss, /@media \(max-width: 420px\) \{[\s\S]*\.nq-modal-backdrop\s*\{[\s\S]*safe-area-inset-bottom[\s\S]*\.nq-modal\s*\{[^}]*safe-area-inset-top/, 'admin compact NQ dialog must preserve safe-area spacing');
assert.match(styleSource, /\.nq-modal \.nq-tabs \{\s*justify-content:\s*center/, 'NQ tab bars must center their tab groups');
assert.match(styleSource, /@media \(max-width: 760px\) \{[\s\S]*\.nq-modal \.nq-tab \{\s*flex:\s*1 1 0[\s\S]*justify-content:\s*center/, 'mobile NQ tabs must split the row into equal centered columns');
assert.match(adminCss, /\.nq-modal \.nq-tabs \{\s*justify-content:\s*center[\s\S]*@media \(max-width: 760px\) \{[\s\S]*\.nq-modal \.nq-tab \{\s*flex:\s*1 1 0[\s\S]*justify-content:\s*center/, 'admin NQ tabs must keep the same centered equal-width mobile layout');
assert.match(adminHtml, /id="sDebugLogs"/, 'admin settings must expose the debug operation log view');
assert.match(adminSource, /<details class="debug-log-details">/, 'debug logs must be collapsible');
assert.doesNotMatch(adminSource, /<details class="debug-log-details" open>/, 'debug logs must be collapsed by default');
assert.match(adminCss, /\.debug-log-details[\s\S]*> summary/, 'debug log details must expose a summary row');
assert.match(adminCss, /\.bulk-target-option\[hidden\]\s*\{\s*display:\s*none/, 'bulk target search must be able to hide filtered options');
assert.match(adminSource, /loadDebugLogs\(\)/, 'settings must load debug operation logs');
assert.match(adminSource, /\/api\/debug\/logs\?limit=200/, 'debug log view must request the bounded latest log set');
assert.match(adminCss, /\.debug-log-row \{[\s\S]*grid-template-columns:/, 'debug log rows must use a stable column grid');
assert.doesNotMatch(adminSource, /mNqReport|id="m(?:Command|Script|Args|Stdin)"|body:\s*JSON\.stringify\(\{[^}]*\b(?:command|script|args|stdin)\b/, 'admin must not accept reports or arbitrary command input');
assert.match(appSource, /Always keep explicit bounds/, 'chart zoom-out must keep explicit x bounds');
assert.match(adminHtml, /id="sGeoIp"/, 'settings must expose the GeoIP provider');
assert.match(adminHtml, /id="sBackup"/, 'settings must expose backup and restore');
assert.match(latencyAgentSource, /"User-Agent": USER_AGENT/, 'Latency agent must avoid Cloudflare rejecting Python urllib requests');
assert.match(latencyAgentSource, /sys\.argv\[1:\] == \["--once"\]/, 'Latency agent must support an installation preflight cycle');
assert.match(latencyAgentSource, /def update_if_needed\(\):/, 'Latency agent must support automatic updates');
assert.match(latencyAgentSource, /\/api\/latency-agent\/update-policy\?node_id=/, 'Latency agent must read the server-side update policy');
assert.match(latencyAgentSource, /policy\.get\("script_version", SCRIPT_VERSION\)/, 'Latency updates must use the server-selected cache version');
assert.match(latencyAgentSource, /os\.replace\(next_path, SCRIPT_PATH\)/, 'Latency agent updates must replace the script atomically');
assert.match(latencyInstallerSource, /latency-agent\.py --once/, 'Latency installer must verify API access before reporting success');
assert.match(latencyInstallerSource, /latency-agent\.py\?v=6/, 'Latency installer must cache-bust the current agent script');
assert.match(latencyAgentSource, /PROBE_TIMEOUT_SEC = 1\.0/, 'external Latency probes must share a strict one-second budget');
assert.match(latencyAgentSource, /socket\.getaddrinfo[\s\S]*threading\.Thread[\s\S]*daemon=True/, 'external Latency probes must race resolved addresses without accumulating per-address timeouts');
assert.match(latencyInstallerSource, /stop_existing_latency_agent\(\)/, 'Latency reinstall must stop all existing agent processes');
assert.match(latencyInstallerSource, /systemctl disable --now nstatus-latency-agent\.service/, 'Latency reinstall must stop and disable the old service');
assert.match(latencyInstallerSource, /pgrep -f '\/opt\/nstatus-latency\/latency-agent\.py'/, 'Latency reinstall must find residual agent processes');
assert.match(latencyInstallerSource, /ReadWritePaths=\/opt\/nstatus-latency/, 'Latency service must allow atomic self-updates inside its sandbox');
assert.match(latencyInstallerSource, /systemctl is-active --quiet nstatus-latency-agent\.service/, 'Latency installer must verify the service is running');

console.log(`frontend syntax tests passed (${files.length} files)`);

async function javascriptFiles(directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await javascriptFiles(absolute));
    else if (entry.isFile() && entry.name.endsWith('.js')) files.push(absolute);
  }
  return files;
}
assert.match(adminSource, /data-a="task-cancel"[\s\S]*data-task-id="\$\{escapeHtml\(task\.id\)\}"/, 'queued or running tasks must expose an admin force-stop button');
assert.match(adminSource, /task\.status === "running" && Number\(task\.cancel_requested_at \|\| 0\) > 0[\s\S]*"停止中"/, 'cancelling tasks must render a visible stopping state');
assert.match(adminSource, /apiAdmin\(`\/api\/agent-tasks\/\$\{encodeURIComponent\(taskId\)\}\/cancel`[\s\S]*method:\s*"POST"/, 'force-stop must call the protected admin cancel route');
assert.match(adminSource, /id="forceStopTask"/, 'task details must expose the force-stop control');
assert.match(adminSource, /if \(b\.dataset\.a === "task-cancel"\) forceStopAgentTask\(b\.dataset\.taskId\);/, 'table actions must wire the force-stop button');
assert.match(adminCss, /\.task-state-wrap\s*\{[\s\S]*display:\s*inline-flex[\s\S]*gap:/, 'task state and force-stop controls must sit on one stable row');
